(define (problem tower-building-problem)
 (:domain blocks-world-multi-agent)
 (:objects A B C D - block A1 A2 - agent)
 (:init
  (on-table A)
  (on-table B)
  (on-table C)
  (on-table D)
  (clear A)
  (clear B)
  (clear C)
  (clear D)
  (empty-hand A1)
  (empty-hand A2)
  (can-handle A1 A)
  (can-handle A1 B)
  (can-handle A2 C)
  (can-handle A2 D)
 )
 (:goal
  (and (on A B) (on B C) (on C D) (on-table D) (clear A))
 )
)